version: '3'

services:
  web-pyspark:
    image : web_pyspark
    build:
      context: ./spark
      dockerfile: Dockerfile
    container_name: web-pyspark
    hostname: web-pyspark
    volumes:
      - ../src/spark:/home/jovyan/work
      - ../text_classification_data:/home/jovyan/text_classification_data
    networks:
      - web_network
    ports:
      - 8080:8080
      - 7077:7077
      - 8888:8888
      - 5000:5000
    restart: always

  web-database:
    image: mysql
    container_name: web-database
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: '123'
    hostname: web-database
    networks:
      - web_network
    volumes:
      - web_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306
    restart: always

volumes:
  web_data:

networks:
  web_network:
    driver: bridge